//Connection Status
export const UPDATE_CONNECTION_TYPE = 'UPDATE_CONNECTION_TYPE'
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS'

//Movies
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_REQUEST_SUCCESS = 'GET_MOVIES_REQUEST_SUCCESS'
export const GET_MOVIES_REQUEST_FAILED = 'GET_MOVIES_REQUEST_FAILED'
export const PAGING_MOVIES_REQUEST = 'PAGING_MOVIES_REQUEST'

//Genre
export const GET_GENRE_REQUEST = 'GET_GENRE_REQUEST'
export const GET_GENRE_REQUEST_SUCCESS = 'GET_GENRE_REQUEST_SUCCESS'
export const GET_GENRE_REQUEST_FAILED = 'GET_GENRE_REQUEST_FAILED'